settings:
  title: 'Status Page'
  url: 'https://baohuo.kangruli.eu.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: 保活լի-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://լի.հայ/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活amy-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.amy.cloudns.be/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活jiner-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.jiner.cloudns.be/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活ju-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.ju.cloudns.be/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活tao-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.tao.cloudns.ch/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活lee-cf
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.lee.cloudns.ch/4d8e3a90-9256-43ad-98f1-7056f9305be4' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活webseek
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://webseek.serv00.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活pack
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://pack.serv00.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: workers-cloudflare-com # unique identifier
    name: 保活package
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://package.serv00.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
